### ISSUE TITLE
TopPage画面でQiita認証ページへ遷移する方法がわからない

### ISSUE THREAD

**Issue by Arugon2002** [shinonome-inc/mobile_Arugon_qiita_app#1]
<img width="380" alt="スクリーンショット 2021-08-19 155005" src="https://user-images.githubusercontent.com/83993322/130078316-cad0bb29-f532-4fcd-b70f-abe039220eac.png">

上の画像のTopPage画面のQiita認証ページへの遷移をするのと、下からベコっとでてくる画面を出すために、

①Flutterで外部のwebサイトへ遷移する方法
https://note.com/blue_69/n/n48cd0013fc6b

②showModalBottomSheet()に関して
https://zenn.dev/mipo/articles/55bcdb282be4a81219bb

を参考に、次のコードを書いてみたのですが、ボトムシート内でQiita認証ページを表示させるやり方が全くわからない上、エラーが出てしまっています。どのようにすればいいか教えて頂きたいです。特に、コードの99行目と106行目以降の書き方が不安です。エラーは添付の画像のように出てきてしまっています。

コードのURL：https://github.com/shinonome-inc/mobile_Arugon_qiita_app/blob/qiita_auth_certfication_page/lib/screens/top_page_screen.dart

エラーの画像：
<img width="449" alt="スクリーンショット 2021-08-19 224817" src="https://user-images.githubusercontent.com/83993322/130080393-f4381e66-f580-4e97-b746-69bfc0e34a34.png">

解決方法に関して教えて頂きたいです。

**Comment by mcz9mm** [comment]
まずAuth認証について調査はしてみたかな？
https://www.youtube.com/watch?v=noDj74dd94M
言語はSwiftだけどGithubAuthの説明がわかりやすいかも
https://qiita.com/yyokii/items/87d4975716f1a6ed620c

FlutterでAuth認証する場合はwebviewを使う必要があるのと
`webview_plugin`を使ってcallback時の受け取りを行う必要がありそうだね。
https://stackoverflow.com/questions/51541258/flutter-login-through-a-webview
https://pub.dev/packages/flutter_webview_plugin

**Comment by mcz9mm** [comment]
この最終課題で一番難しい箇所だから認証は後回しにして他の機能をやるのもありだよ。

**Comment by mcz9mm** [comment]
ちなみにもらったスクショの部分は、`body`はWidgetを設定するところなのに
処理(Future)を設定しててエラーが出てるよ。
本来であればそこにWebViewを設定するべきだと思います。

<img width="645" alt="スクリーンショット 2021-08-20 9 44 15" src="https://user-images.githubusercontent.com/11751495/130161578-ac20582c-825b-4d66-bbc8-bec080b88b80.png">

**Comment by Arugon2002** [comment]
> まずAuth認証について調査はしてみたかな？
> https://www.youtube.com/watch?v=noDj74dd94M
> 言語はSwiftだけどGithubAuthの説明がわかりやすいかも
> https://qiita.com/yyokii/items/87d4975716f1a6ed620c
> 
> FlutterでAuth認証する場合はwebviewを使う必要があるのと
> `webview_plugin`を使ってcallback時の受け取りを行う必要がありそうだね。
> https://stackoverflow.com/questions/51541258/flutter-login-through-a-webview
> https://pub.dev/packages/flutter_webview_plugin

**Comment by Arugon2002** [comment]
OAuth認証に関しては
https://qiita.com/TakahikoKawasaki/items/e37caf50776e00e733be
このページでOAuth認証に関してどんな作業をしているのかはわかりましたが、Flutterでどのようにしたらよいかわからず、
困っていたところでした。
